### ISSUE TITLE
[boj11047] 21줄 이후 while문 성능 향상 질문

### ISSUE THREAD

**Issue by ing03201** [algorithmSSU/guegue#1]
여러 조건을 넣는거보다 한번 내림차순으로 sort하면 코드 줄이 많이 없어질거같습니다

**Comment by rbgus2002** [comment]
하하 저도 너무 조건이 많아서 가독성이 떨어지는 게 느껴지긴 했습니다.
정렬은 int[] coins에 대한 Array 말인가요?
coins Array에 대한 pointer를 하나 만들어주어서 조작하기 때문에 어떤 식으로 정렬을 이용해서 조건문을 줄여야할 지 잘 모르겠습니다. 혹시 구체적으로 말씀해주실 수 있나요???

**Comment by ing03201** [comment]
아 제가 14~17줄을 제대로 안봤네요! 이미 내림차순으로 sorting 되어있는 상태군요!
다만 21줄이후 while문을 for문으로 써도 상관없을거같아요! 제가 내일 한번 수정해서 PR보내도 괜찮을까요?
